# Generated by Django 5.0.11 on 2025-03-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_comment_create_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="auction_type",
            field=models.CharField(
                choices=[("english", "English Auction"), ("dutch", "Dutch Auction")],
                default="english",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="dutch_decrement",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="dutch_decrement_interval",
            field=models.IntegerField(
                blank=True, help_text="Interval in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="dutch_last_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="dutch_reserve_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="dutch_start_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
